# Generated by Django 3.2.9 on 2021-12-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=75)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collegemodel')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
